# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0042_auto_20151218_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='image_description',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
