# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0045_auto_20160228_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsystem',
            name='rotation',
            field=models.TextField(blank=True, default=b'', help_text=b'Rotation around axis for this system'),
        ),
    ]
