# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0046_auto_20160228_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='offset_y_range',
            field=models.CharField(default=b'', help_text=b'JSON: [Two values, in a list]', max_length=100),
        ),
    ]
