# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0047_system_offset_y_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsystem',
            name='offset_y',
            field=models.FloatField(verbose_name=b'Offset for system output', default=5.0),
        ),
        migrations.AlterField(
            model_name='system',
            name='offset_y_range',
            field=models.CharField(help_text=b'JSON: [Two values, in a list]', max_length=100),
        ),
    ]
