# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0048_auto_20160301_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='level',
            field=models.FloatField(default=0, verbose_name=b'Skill level required by user'),
        ),
    ]
