# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0052_auto_20160307_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsystem',
            name='leaderboard',
            field=models.TextField(blank=True, default=b'{"score": -1.0}'),
        ),
        migrations.AlterField(
            model_name='system',
            name='image_description',
            field=models.ImageField(null=True, upload_to=b'rsm'),
        ),
    ]
