# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0054_system_known_optimum_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='known_peak_inputs',
        ),
        migrations.AddField(
            model_name='system',
            name='system_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personsystem',
            name='leaderboard',
            field=models.TextField(blank=True, default=b'[[{"score": -1.0}, 0]]'),
        ),
    ]
