# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0057_experiment_message_while_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='message_while_waiting',
        ),
        migrations.AddField(
            model_name='system',
            name='message_while_waiting',
            field=models.CharField(default=b'', help_text=b"Message to display while 'running' the experiment.'", max_length=510),
        ),
        migrations.AlterField(
            model_name='system',
            name='delay_result',
            field=models.IntegerField(default=0, verbose_name=b'Number of seconds before the result of a SINGLE experiment may be shown to users.'),
        ),
    ]
