# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0058_auto_20160311_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=b''),
        ),
    ]
