# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0059_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsystem',
            name='user_notes',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
